// Artwork actions
export const SET_IMAGE_URL = 'SET_IMAGE_URL';
export const ADD_COMMUNITY = 'ADD_COMMUNITY';
export const REMOVE_COMMUNITY = 'REMOVE_COMMUNITY';
export const SET_TITLE = 'SET_TITLE';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const CHANGE_VISIBILITY = 'CHANGE_VISIBILITY';
export const CLEAR_ARTWORK = 'CLEAR_ARTWORK';

// Settings actions
export const SET_SETTINGS_NAME = 'SET_SETTINGS_NAME';
export const SET_SETTINGS_BIO = 'SET_SETTINGS_BIO';
export const CLEAR_SETTINGS = 'CLEAR_SETTINGS';

// Artworks actions
export const SET_ARTWORKS = 'SET_ARTWORKS';
export const REMOVE_ARTWORKS = 'REMOVE_ARTWORKS';
export const SET_USER_ARTWORKS = 'SET_USER_ARTWORKS';
export const UPDATE_ARTWORK = 'UPDATE_ARTWORK';
export const SET_ARTWORK_COMMENTS = 'SET_ARTWORK_COMMENTS';

// Artwork detail actions
export const SET_ARTWORK_DETAIL = 'SET_ARTWORK_DETAIL';
export const SET_ARTWORK_DETAIL_COMMENTS = 'SET_ARTWORK_DETAIL_COMMENTS';
export const SET_ARTWORK_DETAIL_SCORES = 'SET_ARTWORK_DETAIL_SCORES';
export const REMOVE_ARTWORK_DETAIL = 'REMOVE_ARTWORK_DETAIL';

// Communities actions
export const SET_COMMUNITIES = 'SET_COMMUNITIES';
export const REMOVE_COMMUNITIES = 'REMOVE_COMMUNITIES';

// User actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Gallery User actions
export const SET_GALLERY_USER = 'SET_GALLERY_USER';
export const SET_GALLERY_USER_FOLLOWERS = 'SET_GALLERY_USER_FOLLOWERS';
export const REMOVE_GALLERY_USER = 'REMOVE_GALLERY_USER';

// Scores actions
export const SET_SCORES = 'SET_SCORES';
export const REMOVE_SCORES = 'REMOVE_SCORES';
